#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
name = "Marc de Ferranti"
email = "mezdef@gmail.com"

[merge-tools.nvimdiff]
program = "nvim"

[snapshot]
max-new-file-size = "10MiB"

[ui]
merge-tool = "nvimdiff"
editor = "nvim"
diff-editor = ":builtin"
pager = "diffnav"

[ui.diff]
format = "git"

[merge-tools.codediff]
program = "nvim"
diff-args = ["$left", "$right", "+CodeDiff file $left $right"]

[merge-tools.delta-non-split-view]
program = "delta"
diff-args = [
  "--width",
  "$width",
  "--features",
  "non-split-view",
  "$left",
  "$right",
]

[colors]
# Changeset
"change_id prefix" = { fg = "#b4befe", bold = true }
"change_id rest" = { fg = "#b4befe", dim = true }
"commit_id prefix" = { fg = "#b4befe", bold = true }
"commit_id rest" = { fg = "#b4befe", dim = true }
author = { fg = "#bac2de" }
committer = { fg = "#cdd6f4" }
timestamp = { fg = "#a6adc8" }
description = { fg = "#7f849c" }
"description placeholder" = { fg = "#fab387" }
"empty" = { fg = "#fab387" }
"empty description placeholder" = { fg = "#fab387" }
"bookmark" = "#a6e3a1"
"bookmarks" = "#a6e3a1"
"local_bookmarks" = { fg = "#a6e3a1", dim = true }
"remote_bookmarks" = "#89dceb"
"working_copies" = { fg = "#f5c2e7", dim = true }
"working_copy working_copies" = { fg = "#f5c2e7", dim = false }

"working_copy" = { bold = true }
"node working_copy" = { fg = "#a6e3a1", bold = true }
"working_copy change_id prefix" = { fg = "#1e1e2e", bg = "#a6e3a1", bold = true }
"working_copy change_id rest" = { fg = "#45475a", bg = "#a6e3a1", bold = false, dim = false }
"working_copy commit_id prefix" = { bold = true }
"working_copy commit_id rest" = { dim = true }
"working_copy author" = { bold = true }
"working_copy committer" = { bold = true }
"working_copy timestamp" = { bold = true }
"working_copy description" = { fg = "#a6e3a1", bold = false, dim = false }
"working_copy bookmark" = "#a6e3a1"
"working_copy bookmarks" = "#a6e3a1"
"working_copy local_bookmarks" = { fg = "#a6e3a1", dim = true }
"working_copy remote_bookmarks" = "#89dceb"
"working_copy tag" = "bright magenta"
"working_copy tags" = "bright magenta"
"working_copy git_ref" = "bright green"
"working_copy git_refs" = "bright green"
"working_copy divergent" = "bright magenta"
"working_copy mutable divergent" = "bright red"
"working_copy mutable divergent change_id" = "bright red"
"conflict" = { fg = "#11111b", bg = "red", bold = true }
"working_copy conflict" = { fg = "#11111b", bg = "red", bold = true }
"working_copy empty" = { fg = "#f9e2af", bold = false }
"working_copy placeholder" = { fg = "#f9e2af", bold = false }
"working_copy description placeholder" = { fg = "#f9e2af", bold = false }
"working_copy empty description placeholder" = { fg = "#f9e2af", bold = false }

"diff header" = "yellow"
"diff empty" = "cyan"
"diff binary" = "cyan"
"diff file_header" = { bold = true }
"diff hunk_header" = "cyan"
# Colors - Difftool
"diff context line_number" = { dim = true }
"diff removed" = { fg = "red" }
"diff added" = { fg = "green" }
"diff token" = { underline = false }
# Colors - File changes
"diff modified" = "yellow"
"diff untracked" = "magenta"
"diff renamed" = "cyan"
"diff copied" = "green"
