#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
name = "Marc de Ferranti"
email = "mezdef@gmail.com"

[merge-tools.nvimdiff]
program = "nvim"

[ui]
merge-tool = "nvimdiff"
editor = "nvim"
diff-editor = "nvim"

[custom_commands.open_file]
key = ["o"]
lua = '''
  local file = context.file()
  if not file then
      flash("No file selected")
      return
  end
  exec_shell("nvim " .. file)
'''

[custom_commands.copy_to_clipboard]
key = ["Y"]
lua = '''
local change_id = context.change_id()
if change_id then
    copy_to_clipboard(change_id)
    flash("Copied change ID: " .. change_id)
    return
end
flash("No item selected to copy")
'''
